### ISSUE TITLE
Esphome example.

### ISSUE THREAD

**Issue by dmutpuul** [Botond24/Pelco-Dcode-esphome#1]
Hello. Have you any examples how to work with your component?

**Comment by Botond24** [comment]
Hey, thank you for being interested in my project.
The code example would be
```yaml
external_components:
  - source:
      type: git
      url: https://github.com/Botond24/Pelco-Dcode-esphome

uart:
  tx_pin: 
  rx_pin:
  baud_rate: #the baud rate your Pelco Camera is at
  id: 1

pelco_dcode:
  uart_id: 1
```

Although I have never been able to fully make it work. This component had been mostly abandoned.

**Comment by dmutpuul** [comment]
Thanks for answer) I have motorized mount bracket from China with rs485 control) I want to connect it to my home assistant. And everything that i could find is your component) If i understand i need ttl to rs485 board and then i could try to work with it.

**Comment by Botond24** [comment]
Yes, that is correct, but as I said I'm not even sure the code works. I have a Pelco camera and tried to do the same as you. But I don't remember how it went. At last I didn't connect my camera to homassitant and just used an NVR with rs485 capabilities.

**Comment by dmutpuul** [comment]
One last (but i am not sure) question: how to send commands ? via lambda or what?

**Comment by Botond24** [comment]
Yes via the: `PelcoDcode::send_command(command, data_0, data_1)` in the command you input an int for which the mapping are in the PelcoDProtocolParser.cpp under the enum, the other two are the data you send with the command
For example:
```yaml
api:
  services:
    - service: DownLeft_by_xy
      variables:
        x: int
        y: int
      then:
         !lambda |- PelcoDcode::send_command(17, id (x).state, id (y).state) #but I believe this is the part I haven't been able to do, since there is almost no documentation on how to transfer local variables to a lambda
```

**Comment by Botond24** [comment]
Hey, I started working on this again, but it seems way more difficult than I thought it would be

**Comment by Botond24** [comment]
But it seems like i can use most of the code from modbus

**Comment by Botond24** [comment]
I have finished the new code, but have not been able to test it yet

it should work like so:
```yaml
external_components:
  - source:
      type: git
      url: https://github.com/Botond24/Pelco-Dcode-esphome


uart:
  tx_pin: 
  rx_pin:
  baud_rate: #the baud rate your Pelco Camera is at
  id: rs485

pelco_dcode:
  uart_id: rs485 #optional
  flow_control_pin: #optional
  address: #optional, default = 1

button:
  - platform: pelco_dcode
    send:
      name: "Send"

number:
  - platform: pelco_dcode
    data1: 
      name: "Data1"
    data2:
      name: "Data2"

select:
  - platform: pelco_dcode
    control:
      name: "Command"
```

After setup in hass you should be able to set the command and data to the correct values, this is currently a proof of concept, will change it to work better in the future with simple controls for the ptz function and speed, and etc, but currently it will stay in its current form
